
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adncztqbllxpnowasxwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkbmN6dHFibGx4cG5vd2FzeHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzQ5ODksImV4cCI6MjA1OTYxMDk4OX0.R2holNq9GTuiNbz4hSCUYSGqO_zwAT_VDg_GqOK7nws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define reusable types for use throughout the application
export type Category = Database['public']['Tables']['categories']['Row'];
export type Opportunity = Database['public']['Tables']['opportunities']['Row'];
export type Profile = Database['public']['Tables']['profiles']['Row'];

// Define Application type manually to match the database schema
export type Application = {
  id: string;
  user_id: string;
  opportunity_id: string;
  status: string;
  submitted_date: string;
  last_updated: string;
  notes?: string;
};

// Add Role type
export type UserRole = 'user' | 'admin';
