// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpnwalcqnppymsrjvyzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwbndhbGNxbnBweW1zcmp2eXp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjk4NDgsImV4cCI6MjA2Mzk0NTg0OH0.kAxCrQr7lxHsnZ4bKaSNTUypMCHmvr_ltvSPZnBsmJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);